import type { Report, Summary } from "./api";
import { formatLocalTime } from "./format";

// Shared by both export paths below: a report handed to someone else (an IT professional,
// a support ticket, a saved file) needs to stand on its own — no color-only risk pills, no
// "click to expand reasons," every field spelled out as plain text.

function csvEscape(value: string): string {
  if (/[",\n\r]/.test(value)) return `"${value.replace(/"/g, '""')}"`;
  return value;
}

export function reportsToCSV(items: Report[]): string {
  const header = ["Time", "Risk", "Sender", "Subject", "Source", "Why flagged", "Gmail link"];
  const rows = items.map((r) =>
    [
      formatLocalTime(r.timestamp),
      r.risk,
      r.sender || "",
      r.email_subject || "",
      r.source || "Unknown",
      (r.reasons || []).join("; "),
      r.gmailLink || "",
    ]
      .map((v) => csvEscape(String(v)))
      .join(",")
  );
  return [header.join(","), ...rows].join("\r\n");
}

export function downloadReportsCSV(items: Report[]) {
  const csv = reportsToCSV(items);
  const blob = new Blob(["﻿" + csv], { type: "text/csv;charset=utf-8;" }); // BOM: Excel-safe
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `phishguard-report-${new Date().toISOString().slice(0, 10)}.csv`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/** Opens a clean, dependency-free printable page in a new tab and triggers the browser's
 *  print dialog — "Save as PDF" there is what actually produces the PDF file, so this needs
 *  no PDF library at all. Meant to be handed to someone who never opens the extension: every
 *  risk level and reason is spelled out as text, not a colored pill or a click-to-expand row. */
export function openPrintableReport(items: Report[], summary: Summary | null, scope: string) {
  const generatedAt = new Date().toLocaleString();
  const rows =
    items
      .map(
        (r) => `<tr>
      <td>${escapeHtml(formatLocalTime(r.timestamp))}</td>
      <td class="risk r-${r.risk.toLowerCase()}">${escapeHtml(r.risk)}</td>
      <td>${escapeHtml(r.sender || "—")}</td>
      <td>${escapeHtml(r.email_subject || "—")}</td>
      <td>${escapeHtml(r.source || "Unknown")}</td>
      <td>${escapeHtml((r.reasons || []).join("; ") || "—")}</td>
    </tr>`
      )
      .join("") || `<tr><td colspan="6" class="empty">No emails in this view.</td></tr>`;

  const html = `<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>PhishGuard Report — ${escapeHtml(generatedAt)}</title>
<style>
  * { box-sizing: border-box; }
  body { font-family: -apple-system, "Segoe UI", Arial, sans-serif; color: #10151f; margin: 28px 32px; }
  header { display: flex; align-items: baseline; justify-content: space-between; border-bottom: 2px solid #10151f; padding-bottom: 10px; margin-bottom: 4px; }
  h1 { font-size: 19px; margin: 0; }
  .meta { font-size: 11px; color: #555; margin: 6px 0 18px; }
  .summary { display: flex; gap: 28px; margin-bottom: 20px; }
  .summary div b { display: block; font-size: 18px; }
  .summary div span { font-size: 11px; color: #555; text-transform: uppercase; letter-spacing: .03em; }
  table { width: 100%; border-collapse: collapse; font-size: 11px; }
  th, td { border: 1px solid #ccc; padding: 6px 8px; text-align: left; vertical-align: top; }
  th { background: #f0f1f5; }
  .risk { font-weight: 700; }
  .r-high { color: #b91c1c; }
  .r-medium { color: #b45309; }
  .r-low { color: #047857; }
  .empty { text-align: center; color: #777; padding: 20px; }
  footer { margin-top: 18px; font-size: 10px; color: #888; }
  @media print { @page { margin: 14mm; } }
</style>
</head>
<body>
  <header>
    <h1>PhishGuard Scan Report</h1>
  </header>
  <div class="meta">Generated ${escapeHtml(generatedAt)} — ${escapeHtml(scope)}</div>
  <div class="summary">
    <div><b>${summary?.total ?? items.length}</b><span>Total scanned</span></div>
    <div><b>${summary?.by_risk.Low ?? "—"}</b><span>Low risk</span></div>
    <div><b>${summary?.by_risk.Medium ?? "—"}</b><span>Medium risk</span></div>
    <div><b>${summary?.by_risk.High ?? "—"}</b><span>High risk</span></div>
  </div>
  <table>
    <thead><tr><th>Time</th><th>Risk</th><th>Sender</th><th>Subject</th><th>Source</th><th>Why flagged</th></tr></thead>
    <tbody>${rows}</tbody>
  </table>
  <footer>Generated by PhishGuard. Automated risk assessment — not a certified security verdict.</footer>
</body>
</html>`;

  // No "noopener"/"noreferrer" here on purpose: this opens a blank tab and writes our own
  // generated HTML into it (never a third-party URL), so there's no reverse-tabnabbing risk
  // to guard against — and critically, passing "noopener" makes window.open() return null by
  // spec (the caller deliberately gives up the reference), which was making this look like a
  // blocked popup on every single click, not just when a real popup blocker stepped in.
  const win = window.open("", "_blank");
  if (!win) return false; // an actual popup blocker stepped in — caller should tell the user to allow popups
  win.document.open();
  win.document.write(html);
  win.document.close();
  win.focus();
  // Let the new document finish laying out before invoking print — calling it synchronously
  // can fire before the tab has anything rendered yet, especially on a large table.
  setTimeout(() => win.print(), 300);
  return true;
}
